name: pytest
on:
  push:
    branches:
      - main
    paths:
      - 'src/*'
      - 'tests/*'
      - 'config/*'
      - '.github/workflows/*'
  pull_request:
    branches:
        -main
jobs:
  docker_push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
    container: ghcr.io/${{ env.IMAGE_NAME }}:latest
    steps:
      - uses: actions/checkout@v2
      - run: pytest -s ./tests/
