name: Build and Publish Docker

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
