name: template
on:
  push:
    branches:
      - main
  pull_request:
    branches:
        -main

jobs:
  unit-test:
    timeout-minutes: 10
    name: pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /tmp
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
        with:
          path: /tmp
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest -s ./tests/
