name: template
on: push

jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - run: mkdir /data
      - run: cd /data
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: mkdir log
      - run: mkdir work
      - run: pytest -s ./tests/
